/* eslint-disable jsx-a11y/alt-text */
/* eslint-disable react/no-unescaped-entities */
/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import * as React from "react";
import css from "@/styles/successstories.module.scss";
import axios from "axios";
import { GetServerSidePropsContext } from "next";
import { StoryTypes } from "@/typings/blogs";

export default function SuccessStories({ data }: { data: StoryTypes }) {
  return (
    <>
      <Head>
        <title>Success Stories</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className={css.div1}>
        <h1>
          My<br></br>Success Story
        </h1>
        <img src={"/img/ss.png"} alt="" />
      </section>
      <section className={css.div2}>
        <div className={css.successimg}>
          <img src={data?.image} alt={data?.slug} crossOrigin="anonymous" />
        </div>
        <div className={css.successpara}>
          <h1>{data?.name}</h1>
          <p>{`"${data?.quotes && data?.quotes[0]}"`}</p>
        </div>
      </section>
      <section className={css.div4}>
        <span>
          <img src="/img/Ellipse6.png" alt="" />
        </span>
        <span>
          <img src="/img/j1.png" alt="" />
        </span>
      </section>
      <section
        className={css.div4}
        dangerouslySetInnerHTML={{
          __html: (data?.content && data?.content) as string,
        }}
      ></section>
      <section
        style={{
          overflow: "hidden",
        }}
      ></section>
    </>
  );
}

export const getServerSideProps = async (
  context: GetServerSidePropsContext
) => {
  const { data } = await axios({
    url: `${process.env.NEXT_PUBLIC_BASE_URL}/api/v1/stories/${context.query?.slug}/slug`,
  });

  return {
    props: {
      data,
    },
  };
};
