import Head from "next/head";
import React from "react";
import styles from "@/styles/privacypolicy.module.scss";

export default function TermsCondition() {
  return (
    <>
      <Head>
        <title>Terms Refund Policy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="container2">
        <section className={styles.termsec}>
          <ul>
            <li>
              NEET NAVIGATOR be called and referred to as ‘The First Party’/
              ‘NEET NAVIGATOR’ hereunder.
            </li>
            <li>
              The term subscriber/applicant/candidate shall mean the
              parent/guardian/ward of the candidate, and include the candidate
              who is registered with NEET NAVIGATOR who have affixed their
              signatures in the declaration and application form and shall, for
              the purpose of the services subscribed, together be called and
              referred to as ‘The<b> Second Party’/ ‘Subscriber’</b> hereunder.
            </li>
            <li>
              NEET GUIDE service offered by NEET NAVIGATOR is only limited to
              guidance, information, updates and advices to the subscriber to
              make a suitable career choice. NEET NAVIGATOR only advices and
              assists in choosing suitable courses and institutions as per
              subscriber requirements subject to their performance and
              eligibility (candidate domicile / State Quota / Category/ others)
              as prescribed by the concerned governing authorities.
            </li>
            <li>
              It shall be the discretion of the subscriber to rely or not to
              rely on these guidance, information, updates, advices and
              assistance. NEET NAVIGATOR holds no responsibility if the
              subscriber has made his/her own choice of career.
            </li>
            <li>
              NEET NAVIGATOR is<b> not an agent</b> of medical seats nor does it
              guarantee a confirmed seat, placement or admission for the
              subscriber. NEET NAVIGATOR only assists the subscriber in
              understanding admission process, requirements, eligibilities,
              preconditions, etc., as laid down by various medical councils,
              boards and authorities like NTA, NBE, MCC, NMC, MCI, IMA, NEET,
              etc., and choices available to the subscriber based on the
              performance and information furnished to NEET NAVIGATOR.
            </li>
            <li>
              NEET NAVIGATOR does not take any liabilities if the subscriber
              fails to get a seat or admission for non-fulfilment of
              eligibilities, preconditions, etc., as laid down by various
              medical councils, boards and authorities like NTA, NBE, MCC, NMC,
              MCI, IMA, NEET, etc., underperformance and any other bars and
              conditions laid down by concerned institution which would render
              the subscriber ineligible for any course or admission. NEET
              NAVIGATOR does not take any liabilities if the subscriber fails to
              get a seat or admission due to decisions taken by the admission
              controlling bodies, authorities and institutions.
            </li>
            <li>
              NEET NAVIGATOR only assists and facilitates the subscriber in
              seeking all information about the NEET Counselling process subject
              to the service package opted by the applicant.
            </li>
            <li>
              NEET NAVIGATOR provides updates, information and opinions based on
              past analysis, research, experience and expertise. The said
              updates and information may change from time to time upon
              happening and non-happening of uncertain events and developments.
              NEET NAVIGATOR does not hold responsibilities in such cases.
            </li>
            <li>
              NEET NAVIGATOR proceeds with various process assuming in good
              faith that the documents and information provided by the candidate
              are genuine and accurate as per the declaration. NEET NAVIGATOR
              shall not be responsible if the subscriber fails to get a seat or
              admission due to default committed by the subscriber in cases
              where there is delay in furnishing relevant information and
              documents, or produces faulty and incomplete documents or fails to
              communicate decisions on time as orally prescribed by NEET
              NAVIGATOR.
            </li>
            <li>
              NEET NAVIGATOR helps the candidate by advising and guiding the
              subscriber for seeking admission for various courses, subject to
              the eligibility, performance and information furnished by the
              subscriber and does not guarantee any seat, admission to any
              course or institution.
            </li>
            <li>
              NEET NAVIGATOR does not undertake liabilities for mistakes
              committed while filling up various forms and applications of the
              subscriber both online and offline. The subscriber shall be
              entirely responsible for all mistakes and errors committed therein
              even if filled by NEET NAVIGATOR as per subscriber request. NEET
              NAVIGATOR does not undertake responsibilities and liabilities, if
              alerts or notifications are missed.
            </li>
            <li>
              NEET NAVIGATOR is not bound by any verbal commitments made by any
              of its employee/s or representative/s. It shall not be held
              responsible for any such representation made and its consequences.
            </li>
            <li>
              “NEET GUIDE” offered by NEET NAVIGATOR is inclusive of the listed
              services as per the subscribed NEET GUIDE Service package and
              detailed in the Service Sheet. Services under NEET GUIDE PACKAGE
              will last up to the end of NEET 2022 Counselling. Any amount
              payable to the Counseling Board / Authority if any such like;
              application fee, registration fee is not included and shall be
              payable by the subscriber directly.
            </li>
            <li>
              <b>
                “NEET GUIDE service” registration/subscription fee once paid
                shall not be refundable under any circumstances.
              </b>
            </li>
            <li>
              NEET NAVIGATOR after making all efforts, subject to requirements,
              eligibilities, preconditions, etc., as laid down by various
              medical councils, boards and authorities like NTA, NBE, MCC, NMC,
              MCI, IMA, NEET, etc., fails to seek enrollment/seat/admission in
              the preferred institute/ state/ course based on the eligibility
              and performance of the subscriber or if the subscriber chooses to
              terminate the services or opt out, NEET NAVIGATOR shall not be
              liable to refund any amount.
            </li>
            <li>
              NEET NAVIGATOR reserves the rights to sue the subscriber if in
              case it is found out that the subscriber has played fraud,
              fabricated documents, furnished wrong and false information. In
              such cases, NEET NAVIGATOR shall terminate the subscription and
              the subscription fee paid shall be deemed to be forfeited in its
              favor.
            </li>
            <li>
              NEET NAVIGATOR ON Demand Service is a separate service package
              which is not the part of NEET GUIDE Service package.
            </li>
            <li>
              All disputes of civil nature shall, arising out this service
              agreement, be referred to arbitration. In the event of any
              conflict, dispute or difference between the parties hereto on any
              matter in question, dispute or differences on any account shall be
              first referred to the senior management of the NEET NAVIGATOR for
              amicable settlement. If the same is not settled within five (5)
              days of referring the same to the senior management, the same
              shall be referred and settled by a sole arbitrator mutually
              appointed by the parties, under the provisions of the Arbitration
              and Conciliation Act, 1996 as amended from time to time. The sole
              arbitrator shall a person qualified and experienced in the subject
              matter of arbitration. The arbitration proceedings shall take
              place in English language. The seat of arbitration shall be at
              Delhi. The governing laws shall be Indian laws. The parties herein
              shall equally bear all costs associated with such arbitration
              process.
            </li>
          </ul>
        </section>
      </section>
    </>
  );
}
