/* eslint-disable react/no-unescaped-entities */
/* eslint-disable @next/next/no-img-element */
import React from "react";
import Head from "next/head";

export default function AboutUs() {
  return (
    <>
      <Head>
        <title>About Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section>
        <div className="banner">
          <div className="left-bannerPart  animate__animated animate__zoomInDown">
            <h1>
              Guiding students to the dream <span>medical college.</span>
            </h1>
          </div>
          <div className="right-bannerPart">
            <img
              src="/img/bannerLatest.jpg"
              alt="bannerLatest"
              className="animate__animated animate__bounceInRight"
            />
          </div>
        </div>
      </section>
      <section>
        <div className="container">
          <div className="about-intro">
            <h2>
              Why we are<span> Here?</span>
            </h2>
            <p className="first-intro">
              Medical admission counselling guidance is a field infamous for
              corruption and cheating. It’s an ocean full of sharks which makes
              many medical aspirants scared of seeking professional guidance.
            </p>
            <p className="second-intro">
              At NEET Navigator, we understand that the medical admission
              process in India is complex, confusing, and highly competitive.
              That's why we are working to integrate most advanced data
              analytics to help students succeed in their medical admission.
            </p>
          </div>
        </div>
      </section>
      <section>
        <div className="our-mission container">
          <div className="our-missionText">
            <h2>
              Our <span>Mission</span>
            </h2>
            <p>
              NEET Navigator is on a mission to create India’s First GPS to MBBS
              Admission. We are working to offer most accurate and ethical
              guidance for medical admission counseling in India. We want to
              ensure that every NEET aspirant shall get the fair chance of
              admission.
            </p>
          </div>
          <div className="our-missionImage">
            <img src="/img/person.png" alt="" />
            <div className="founder">
              <span>Rakesh Jain</span>
              <span id="block">Founder of NEET NAVIGATOR</span>
            </div>
          </div>
        </div>
      </section>
      <section>
        <div className="container">
          <div className="ourTeam">
            <h2>
              Our <span>Team</span>
            </h2>
            <p>
              NEET Navigator is a team of seasoned and successful members who
              has gained deep insights in field of medical admission counselling
              and data analytics. The team is advised by a board which consists
              of renowned professionals from industry, medicine and academics.
            </p>
            <div className="team-cards">
              {popArray.map((Value, index) => {
                return (
                  <div className="rakesh" key={index}>
                    <div className="rakesh-image">
                      <img src={Value.url} alt="" />
                    </div>
                    <div className="rakeshText">
                      <h3>{Value.heading}</h3>
                      {/* <p style={{ fontSize: 14, textAlign: "justify" }}>
                      </p> */}
                      <ReactReadMoreReadLess>
                        {Value.content}
                      </ReactReadMoreReadLess>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      </section>
      <section>
        <div className="propositions">
          <div className="propositions-leftPart">
            <h2>
              Value<span> Proposition</span>
            </h2>
            <p>
              In the ocean full of sharks, NEET Navigator is the dolphin in the
              shark tank. NEET Navigator value is defined by the ethics and
              honesty.
            </p>
          </div>
          <div className="propositions-rightPart">
            <div className="props-cards" id="firstProp">
              <div className="flipbox">
                <div className="first">
                  <img src="/img/ANALYTICAL.png" alt="" />
                  <h3> Data Analytics</h3>
                </div>
                <div className="back">
                  <p>
                    NEET Navigator shifts the focus of decision making from Gut
                    to Data. NEET Navigator uses advanced data analytics to
                    guide you for admission in The Best Medical college based on
                    your NEET Rank, Domicile, Category and Fee Budget.
                  </p>
                </div>
              </div>
            </div>
            <div className="props-cards" id="secondProp">
              <div className="flipbox">
                <div className="first">
                  <img src="/img/COMPRHENSIVE.png" alt="" />
                  <h3> Comprehensive</h3>
                </div>
                <div className="back">
                  <p>
                    NEET Navigator mines, collates and analyses the most
                    comprehensive data from all states and MCC medical admission
                    counselling. The comprehensive data expands the horizon of
                    available admission opportunities for medical aspirants.
                  </p>
                </div>
              </div>
            </div>
            <div className="props-cards" id="thirdProp">
              <div className="flipbox">
                <div className="first">
                  <img src="./img/ETHICAL AND TRUSTWORTHY.png" alt="" />
                  <h3> Ethical and trustworthy</h3>
                </div>
                <div className="back">
                  <p>
                    Medical admission counselling guidance is a field infamous
                    for corruption and cheating. NEET Navigator is managed by
                    renowned professionals from Industry and Academia. NEET
                    Navigator offers transparent and trustworthy services in the
                    most ethical manner.
                  </p>
                </div>
              </div>
            </div>
            <div className="props-cards" id="fourthProp">
              <div className="flipbox">
                <div className="first">
                  <img src="./img/EMPATHIC APPROACH.png" alt="" id="differ" />
                  <h3> Empathetic Approach</h3>
                </div>
                <div className="back">
                  <p>
                    NEET Navigator offers the most empathetic communication and
                    humane approach to entire medical admission counselling
                    process so that students and parents can have a stress-free
                    journey to their dream medical college.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section>
        <div className="container">
          <div className="testimonials p-0">
            <h2>
              Videos<span> Testimonials</span>
            </h2>
            <div className="testimonial-grid">
              <div className="first-testimonialSection">
                <img src="/img/testimonial/01.jpeg" alt="testimonials image" />
              </div>
              <div className="second-testimonialSection">
                <img src="/img/testimonial/02.jpeg" alt="testimonials image" />
                <img src="/img/testimonial/03.jpeg" alt="testimonials image" />
              </div>
            </div>
          </div>
        </div>
      </section>

      <section>
        <div className="our-story container">
          <h2>
            Our <span>Story</span>
          </h2>
          <div className="story-grid">
            <div className="our-storyLeft">
              <iframe
                width={560}
                height={315}
                src="https://www.youtube.com/embed/I1Epcnmh1Pk"
                title="YouTube video player"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                allowFullScreen
              />
            </div>
            <div className="our-storyRight">
              <p>
                NEET NAVIGATOR started in 2019 with advisory and training
                services to institutional clients and in 2021 NEET NAVIGATOR
                launched the personalised counselling services for
                students/parents. Over years we have achieved 95% success rate
                for MBBS admission into Government, Private and Deemed Medical
                Colleges. NEET NAVIGATOR was First in India who laid the
                foundation of data analysis based ethical medical admission
                counselling. NEET NAVIGATOR has developed Big Data based
                Probability Algorithms to create highly accurate decision making
                models for Medical admission .
              </p>
            </div>
          </div>
        </div>
      </section>
      <section>
        <div className="poem-section container">
          <h2>
            “A NEET’s Guide to <span>Navigating Life”</span>
          </h2>
          <div className="poem">
            <div className="first-poem">
              <div className="poem-firstLeft">
                <img src="/img/poem1.png" alt="" />
              </div>
              <div className="poem-firstRight">
                <p>
                  NEET Navigator, guide so true,
                  <br /> Helping students find their way through,
                  <br /> With data-backed decisions, never skew,
                  <br /> A beacon of hope, shining bright and new
                </p>
              </div>
            </div>
            <div className="second-poem">
              <div className="poem-secondLeft">
                <p>
                  Other counselors may make false claims,
                  <br /> Promising the impossible, playing games,
                  <br /> But NEET Navigator, true to its name,
                  <br />
                  Leads students to the best medical college, with no shame.
                </p>
              </div>
              <div className="poem-secondRight">
                <img src="/img/poem2.png" alt="" />
              </div>
            </div>
            <div className="third-poem">
              <div className="poem-thirdLeft">
                <img src="/img/poem3.png" alt="" />
              </div>
              <div className="poem-thirdRight">
                <p>
                  Honest and forthright, always fair,
                  <br /> NEET Navigator, a breath of fresh air,
                  <br /> For those seeking a medical career,
                  <br /> It's a beacon of hope, shining ever so clear.
                </p>
              </div>
            </div>
            <div className="fourth-poem">
              <div className="poem-fourthLeft">
                <p>
                  So let NEET Navigator be your guide,
                  <br /> As you navigate the path to success with pride,
                  <br /> With its help, you'll reach the other side,
                  <br />
                  To a future in medicine, where you'll reside.
                </p>
              </div>
              <div className="poem-fourthRight">
                <img src="/img/poem4.png" alt="" />
              </div>
            </div>
          </div>
        </div>
      </section>
      <section>
        <div className="container">
          <div className="success">
            <img src="/img/quote1.png" alt="" />
            <span>
              Success is making those who believed in you look
              <span> brilliant.</span>
            </span>
            <img src="/img/quote2.png" alt="" />
          </div>
          <div className="signatory">
            <div className="signatory-name">
              <h3>Rakesh Jain</h3>
              <p>Founder of NEET NAVIGATOR</p>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}

const ReactReadMoreReadLess = ({ children }: T) => {
  const [showMore, setShowMore] = React.useState(false);

  const onShowMore = React.useCallback(() => {
    setShowMore(!showMore);
  }, [showMore]);
  return (
    <React.Fragment>
      <div className="ReactReadMoreReadLess newtextrt">
        <p
          style={{
            display: "-webkit-box",
            WebkitLineClamp: showMore ? "10" : "3",
            WebkitBoxOrient: "vertical",
            overflow: "hidden",
            transition: "all 200ms ease",
            fontSize: 14,
            textAlign: "justify",
            marginBottom: "0px !important",
          }}
        >
          {children}
        </p>
        <a onClick={onShowMore} className="ReactReadMoreReadLess">
          {showMore ? "Read Less" : "Read More"}
        </a>
      </div>
    </React.Fragment>
  );
};

const popArray = [
  {
    url: "/img/rakesh-jain.jpg",
    heading: "Rakesh Jain",
    content:
      "Rakesh is among the founder members of NEET Navigator. Rakesh studied at FMS-Delhi and IIM- A. He brings a rich experience of over 20 years in industry at most senior levels as Head-HR and over 5 years of academic experience as associate professor. Rakesh is currently leading the organization and counselling processes at NEET Navigator.",
  },
  {
    url: "/img/vibhuti.jpg",
    heading: "Vibhuti Venkat Nataraj",
    content:
      "Vibhuti Venkat Nataraj is a seasoned data scientist and a master statistician. Currently located in New Zealand, he started his career with TCS after doing his masters in statistics from Indian Statistical Institute Calcutta in 1996. Vibhu is spearheading NEET Navigator’s data management team towards creating GPS to MBBS admission.",
  },
  {
    url: "/img/ML.jpeg",
    heading: "Dr. M. L. Singla",
    content:
      "Dr. Singla is among the pioneers of data sciences and IT management in India. He started his journey with TCS in early 80’s and subsequently moved to teaching at FMS- Delhi. He has been one of most revered dean and professor at FMS- Delhi, MDI and California State University. He is guiding NEET Navigator on its journey of value creation. ",
  },
];
