/* eslint-disable react/no-unescaped-entities */
/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/blogs.module.scss";
import * as React from "react";
import { Blogs } from "network-requests/types";
import { useGetAllBlogs } from "@/network-requests/queries";
import Link from "next/link";

export default function Blogs() {
  const { data, refetch } = useGetAllBlogs();
  return (
    <>
      <Head>
        <title>Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className={styles.mydiv55}>
        <h1>Blogs</h1>
      </section>

      <section className={styles.blogcard}>
        <ul>
          {data?.map((list, index) => {
            console.log(list);
            return (
              <li key={index}>
                <div className={styles.box1}>
                  <img src={list.images[0]} alt="img" />
                  <div className={styles.boxcontent}>
                    <h2>{list.name}</h2>
                    <div
                      dangerouslySetInnerHTML={{
                        __html: list.content.slice(0, 100),
                      }}
                    ></div>
                    <Link href={`/blogs/${list.slug}`}>Read More</Link>
                  </div>
                </div>
              </li>
            );
          })}
          
          
        </ul>
      </section>
    </>
  );
}
