/* eslint-disable react/no-unescaped-entities */
/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/blogs.module.scss";
import * as React from "react";

export default function Blogs() {
  return (
    <>
      <Head>
        <title>Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className={styles.mydiv55}>
        <h1>krishna</h1>
      </section>

      <section className={styles.blogcard}>
        <ul>
          <li>
            <div className={styles.box1}>
              <img src="/image/anikajain.jpg" alt="img" />
              <h2>What is a Divan Bed? Here’s Everything You Need to Know</h2>
              <p>
                Lorem Ipsum is simply dummy text of the printing and typesetting
                industry. Lorem Ipsum has been the industry's standard dummy
                text ever since the 1500s, when an unknown printer took a galley
                of type and scrambled it to make a type specimen book. It has
                survived not only five centuries, but also the leap into
                electronic typesetting, remaining essentially unchanged.
              </p>
              <a href="#">Read More</a>
            </div>
          </li>
        </ul>
      </section>
    </>
  );
}
